import java.io.*;
//import java.util.*;

public class Input{
	
	public static void main(String args[]) throws IOException{
		
		String DNA1, DNA2;
		DNA1="TAGCTACGTAGCTAGCTACGTACGTCGATCGTAGCTAGTAGTCGTAGCTACGTAGCTACGTACGTACGTACGTACGTAATCGATCGACTAATTACGATCGCATACGATCGATCGAATCGATCGACTAATTACGATCGCATACGATCGATCGATCGATCGATCGATCGACTGATCGTCGATCGATCGATCTCGATTCGTACATCGAAAATCGTCGATCTAAGCTCGATCGATCGATCGACTGATCGACTGACTACGGACTGATCGCGTACGTCGTCGATGACTGATCGTCGATCGTACGTACTACGTACGTAGTACGTCGATCGTACGTACGATCGATCGTAGCTCAGTGCATGATGATGTAGTACGTGACTGCAACGTACGATCGATACGATATC";
		DNA2="ATCGATGATCGACTAGCATCGATCGACTAATTACGATCGCATACGATCGATCGATTCGTACATCGAAAATCGTCGATCTAAGCTCGATCGATCGATCGACTGATCGACTGACTACGATCGATCGTAGCTACGTATCGATTCGTACATCGAAAATCGTCGATCTAAGCTCGATCGATCGATCGACTGATCGACTGACTACGCGATCGTACATCGAAAATCGTGATCGTCGATCGATCGATCTCGATTCGTACATCGAAAACGATCTAAGCTACGTACGTACGATCGATCGTACGATGATTAGCATCGTACGATCACTAGACATCGATCGATCGACGATCGATCGATCGATCATCATCGATCACTACGATGCATCGATGATCACTACG";
		/*Scanner scanner = new Scanner(System.in);
		DNA1 = scanner.nextLine();
		System.out.println("Your DNA is: " + DNA1);
		DNA2 = scanner.nextLine();
		System.out.println("XXX DNA is: " + DNA2);
		scanner.close();*/
		
		
		CostMatrix costmatrix =new CostMatrix();
		costmatrix.FillMatrix(DNA1, DNA2);
	}
}
